name = "ccas-website"
compatibility_date = "2026-07-29"

[build]
command = "npm run build"
cwd = "client"
watch_dir = ["client/src", "client/public", "client/index.html", "client/vite.config.js"]

[assets]
directory = "./client/dist"
not_found_handling = "single-page-application"
