import {
  BarChart,
  Bell,
  Calendar,
  FileHeart,
  Home,
  Settings,
  Shield,
  Stethoscope,
  Users,
} from "lucide-react";

export const ROLE_PAGES = {
  patient: [
    "overview",
    "appointments",
    "doctors",
    "history",
    "notifications",
    "account",
  ],
  receptionist: [
    "overview",
    "appointments",
    "patients",
    "doctors",
    "walk-in",
    "notifications",
    "account",
  ],
  doctor: [
    "overview",
    "appointments",
    "patients",
    "doctors",
    "history",
    "notifications",
    "account",
  ],
  nurse: [
    "overview",
    "appointments",
    "patients",
    "doctors",
    "notifications",
    "account",
  ],
  manager: ["overview", "reports", "doctors", "notifications", "account"],
  admin: [
    "overview",
    "appointments",
    "patients",
    "doctors",
    "history",
    "reports",
    "admin",
    "notifications",
    "account",
  ],
};

export const NAV_ITEMS = {
  overview: { label: "Overview", icon: Home, section: "Workspace" },
  appointments: { label: "Appointments", icon: Calendar, section: "Workspace" },
  patients: { label: "Patients", icon: Users, section: "Clinic" },
  doctors: { label: "Doctors", icon: Stethoscope, section: "Clinic" },
  history: { label: "Medical History", icon: FileHeart, section: "Clinic" },
  reports: { label: "Reports", icon: BarChart, section: "Management" },
  admin: { label: "Administration", icon: Shield, section: "Management" },
  "walk-in": { label: "Walk-In", icon: Users, section: "Clinic" },
  notifications: { label: "Notifications", icon: Bell, section: "Account" },
  account: { label: "My Account", icon: Settings, section: "Account" },
};
